/*
* generated by Xtext
*/
package org.eclipse.elk.graphviz.dot.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class GraphvizDotAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/eclipse/elk/graphviz/dot/parser/antlr/internal/InternalGraphvizDot.tokens");
	}
}
