<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="klayoutdata" nsURI="http://elk.eclipse.org/KLayoutData" nsPrefix="klayoutdata">
  <eClassifiers xsi:type="ecore:EClass" name="KShapeLayout" eSuperTypes="#//KLayoutData">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This layout data contains information for graph elements for which rectangular&#xA;shape is assumed for layout, such as nodes, ports, and labels. Each graph element&#xA;has either a shape layout or an edge layout attached. The shape layout of nodes&#xA;has insets.&#xA;&lt;p>&#xA;Layout coordinates for nodes, ports, and node labels are relative to the parent&#xA;node. The insets of the parent node are not included in the relative coordinates&#xA;of child nodes, but they are included in the relative coordinates of ports and&#xA;node labels. For edge labels the rules defined in {@link KEdgeLayout} apply.&#xA;Port labels are relative to their ports.&#xA;&lt;/p>"/>
    </eAnnotations>
    <eOperations name="setPos">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Set the position of this shape layout.&#xA;@param x the new x coordinate value&#xA;@param y the new y coordinate value"/>
      </eAnnotations>
      <eParameters name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eParameters name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    </eOperations>
    <eOperations name="applyVector">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Set the position of this shape layout by applying the given vector.&#xA;@param pos the vector for the new position"/>
      </eAnnotations>
      <eParameters name="pos" eType="#//KVector"/>
    </eOperations>
    <eOperations name="createVector" eType="#//KVector">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Create a vector from the position of this shape layout.&#xA;@return the position vector"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="setSize">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Set the size of this shape layout.&#xA;@param width the new width&#xA;@param height the new height"/>
      </eAnnotations>
      <eParameters name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eParameters name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xpos" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="0.0f"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ypos" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="0.0f"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="0.0f"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="0.0f"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="insets" eType="#//KInsets"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KEdgeLayout" eSuperTypes="#//KLayoutData">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This layout data contains special information for edges, such as bend points.&#xA;Each graph element has either a shape layout or an edge layout attached.&#xA;&lt;p>&#xA;All layout coordinates for edges are defined to be relative to the parent of&#xA;the source node, except when the target node is directly or indirectly contained&#xA;in the source node, in which case all coordinates are relative to the source node&#xA;itself. The insets of the reference node are not included in relative coordinates.&#xA;&lt;/p>"/>
    </eAnnotations>
    <eOperations name="applyVectorChain">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Set the source point, bend points, and target point of this edge layout&#xA;from the given vector chain. The vector chain should contain at least&#xA;two points; the first point is taken as source point, while the last one is&#xA;taken as target point.&#xA;@param points the new points for this edge layout"/>
      </eAnnotations>
      <eParameters name="points" eType="#//KVectorChain"/>
    </eOperations>
    <eOperations name="createVectorChain" eType="#//KVectorChain">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Create a vector chain from the points of this edge layout. The resulting&#xA;vector chain contains at least two points; the first point is the source point,&#xA;while the last one is the target point.&#xA;@return the points of this edge layout"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bendPoints" upperBound="-1"
        eType="#//KPoint" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The coordinates of bend points must obey the general rules for edge&#xA;coordinates defined above."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourcePoint" lowerBound="1"
        eType="#//KPoint" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The source point is the point at which the edge touches the source node&#xA;or source port. The coordinates of source points must obey the general&#xA;rules for edge coordinates defined above."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetPoint" lowerBound="1"
        eType="#//KPoint" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The target point is the point at which the edge touches the target node&#xA;or target port. The coordinates of target points must obey the general&#xA;rules for edge coordinates defined above."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KLayoutData" abstract="true" interface="true"
      eSuperTypes="../../org.eclipse.elk.graph/model/kgraph.ecore#//KGraphData">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Common interface for shape layouts and edge layouts. Shape layouts are&#xA;used by nodes, ports, and labels, while edge layouts are used by edges."/>
    </eAnnotations>
    <eOperations name="isModified" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Whether the concrete layout data have been modified since the layout data instance&#xA;was created or the modification flag was reset. For shape layouts this refers to the&#xA;position or size, and for edge layouts it refers to the source point, target point, or&#xA;bend points."/>
      </eAnnotations>
    </eOperations>
    <eOperations name="resetModificationFlag">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Reset the modification flag to {@code false}. Layout algorithms should not do this."/>
      </eAnnotations>
    </eOperations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KPoint">
    <eOperations name="setPos">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Set a new position for this point.&#xA;@param x the new x coordinate value&#xA;@param y the new y coordinate value"/>
      </eAnnotations>
      <eParameters name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eParameters name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    </eOperations>
    <eOperations name="applyVector">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Set the position of this point using a vector.&#xA;@param pos the vector for the new position"/>
      </eAnnotations>
      <eParameters name="pos" eType="#//KVector"/>
    </eOperations>
    <eOperations name="createVector" eType="#//KVector">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Create a vector from this point.&#xA;@return a vector with the position of this point"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="0.0f"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="0.0f"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KInsets">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Insets specify the amount of space that is required between the&#xA;children of a node and the node's boundary. Usually the inset values must&#xA;be added to the bounding box of the contained subgraph."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="top" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This is the minimal distance to the top side of a parent node."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bottom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This is the minimal distance to the bottom side of a parent node."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="left" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This is the minimal distance to the left side of a parent node."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="right" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KIdentifier" eSuperTypes="../../org.eclipse.elk.graph/model/kgraph.ecore#//KGraphData">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Can be used for unique identification of KGraph elements."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KVector" instanceClassName="org.eclipse.elk.core.math.KVector"
      abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KVectorChain" instanceClassName="org.eclipse.elk.core.math.KVectorChain"
      abstract="true" interface="true"/>
</ecore:EPackage>
